sudo rm  *.dtbo
sudo rm  *.order
sudo rm  *.symvers
sudo rm  ./fbtft/*.o
sudo rm  ./fbtft/*.ko
sudo rm  ./fbtft/*.mod.c
sudo rm  ./fbtft/*.mod.o
sudo rm  ./fbtft/*.mod
sudo rm  ./fbtft/*.order
sudo rm  ./touch/*.o
sudo rm  ./touch/*.ko
sudo rm  ./touch/*.mod.c
sudo rm  ./touch/*.mod.o
sudo rm  ./touch/*.mod
